Develop marge java21
mosip/packet-manager pull request #156
Opened 2024-06-18 12:58 UTC by Khuddusshariff0022

2024-06-19 10:21 UTC, sowmya695 commented on .github/workflows/push-trigger.yml
kattu branch name change is needed

2024-06-19 10:33 UTC, sowmya695 commented on commons-packet/commons-packet-service/src/main/java/io/mosip/commons/packetmanager/controller/PacketReaderController.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
Remove this unused import

2024-06-19 10:35 UTC, sowmya695 requested changes
Please fix the review comment

2024-06-20 07:43 UTC, Khuddusshariff0022 commented on .github/workflows/push-trigger.yml
done

2024-06-20 09:50 UTC, Khuddusshariff0022 commented on commons-packet/commons-packet-service/src/main/java/io/mosip/commons/packetmanager/controller/PacketReaderController.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
done

2024-06-21 05:54 UTC, sowmya695 approved these changes

2024-06-21 11:46 UTC, ckm007 approved these changes

2024-06-21 11:47 UTC, merged